# Form implementation generated from reading ui file 'Data_Export.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Data_export(object):
    def setupUi(self, Data_export):
        Data_export.setObjectName("Data_export")
        Data_export.resize(400, 300)
        Data_export.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Data_export)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textEdit = QtWidgets.QTextEdit(Data_export)
        self.textEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.button_box = QtWidgets.QHBoxLayout()
        self.button_box.setContentsMargins(-1, 5, -1, -1)
        self.button_box.setSpacing(10)
        self.button_box.setObjectName("button_box")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.button_box.addItem(spacerItem)
        self.button_ok = QtWidgets.QPushButton(Data_export)
        self.button_ok.setMinimumSize(QtCore.QSize(80, 30))
        self.button_ok.setMaximumSize(QtCore.QSize(80, 30))
        self.button_ok.setStyleSheet("background-color: rgb(223, 223, 223)")
        self.button_ok.setAutoDefault(False)
        self.button_ok.setObjectName("button_ok")
        self.button_box.addWidget(self.button_ok)
        self.button_copy_to_clipboard = QtWidgets.QPushButton(Data_export)
        self.button_copy_to_clipboard.setMinimumSize(QtCore.QSize(80, 30))
        self.button_copy_to_clipboard.setMaximumSize(QtCore.QSize(80, 30))
        self.button_copy_to_clipboard.setStyleSheet("background-color: rgb(223, 223, 223)")
        self.button_copy_to_clipboard.setAutoDefault(False)
        self.button_copy_to_clipboard.setObjectName("button_copy_to_clipboard")
        self.button_box.addWidget(self.button_copy_to_clipboard)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.button_box.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.button_box)

        self.retranslateUi(Data_export)
        self.button_ok.clicked.connect(Data_export.close)
        QtCore.QMetaObject.connectSlotsByName(Data_export)

    def retranslateUi(self, Data_export):
        _translate = QtCore.QCoreApplication.translate
        Data_export.setWindowTitle(_translate("Data_export", "Eksport danych"))
        self.button_ok.setText(_translate("Data_export", "Ok"))
        self.button_ok.setShortcut(_translate("Data_export", "Return"))
        self.button_copy_to_clipboard.setText(_translate("Data_export", "Kopiuj"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Data_export = QtWidgets.QDialog()
    ui = Ui_Data_export()
    ui.setupUi(Data_export)
    Data_export.show()
    sys.exit(app.exec())
