# Form implementation generated from reading ui file 'Import_Error.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Error_import(object):
    def setupUi(self, Error_import):
        Error_import.setObjectName("Error_import")
        Error_import.resize(400, 130)
        Error_import.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Error_import)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.error_text = QtWidgets.QLabel(Error_import)
        self.error_text.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.error_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.error_text.setWordWrap(True)
        self.error_text.setObjectName("error_text")
        self.verticalLayout.addWidget(self.error_text)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.button_ok = QtWidgets.QPushButton(Error_import)
        self.button_ok.setMinimumSize(QtCore.QSize(80, 30))
        self.button_ok.setMaximumSize(QtCore.QSize(80, 30))
        self.button_ok.setStyleSheet("background-color: rgb(223, 223, 223)")
        self.button_ok.setAutoDefault(False)
        self.button_ok.setObjectName("button_ok")
        self.horizontalLayout.addWidget(self.button_ok)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Error_import)
        self.button_ok.clicked.connect(Error_import.close)
        QtCore.QMetaObject.connectSlotsByName(Error_import)

    def retranslateUi(self, Error_import):
        _translate = QtCore.QCoreApplication.translate
        Error_import.setWindowTitle(_translate("Error_import", "Bład importu"))
        self.error_text.setText(_translate("Error_import", "TextLabel"))
        self.button_ok.setText(_translate("Error_import", "Ok"))
        self.button_ok.setShortcut(_translate("Error_import", "Return"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Error_import = QtWidgets.QDialog()
    ui = Ui_Error_import()
    ui.setupUi(Error_import)
    Error_import.show()
    sys.exit(app.exec())
