# Form implementation generated from reading ui file 'Size_Change_Widget.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Size_change_popup(object):
    def setupUi(self, Size_change_popup):
        Size_change_popup.setObjectName("Size_change_popup")
        Size_change_popup.resize(255, 170)
        Size_change_popup.setMinimumSize(QtCore.QSize(255, 170))
        Size_change_popup.setMaximumSize(QtCore.QSize(255, 170))
        Size_change_popup.setStyleSheet("background-color: rgb(200, 200, 200);")
        Size_change_popup.setSizeGripEnabled(False)
        Size_change_popup.setModal(False)
        self.buttonBox = QtWidgets.QDialogButtonBox(Size_change_popup)
        self.buttonBox.setGeometry(QtCore.QRect(25, 114, 205, 30))
        self.buttonBox.setStyleSheet("background-color: rgb(223, 223, 223)")
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.height = QtWidgets.QSpinBox(Size_change_popup)
        self.height.setGeometry(QtCore.QRect(105, 25, 120, 30))
        self.height.setStyleSheet("background-color: rgb(223, 223, 223)")
        self.height.setMinimum(1)
        self.height.setMaximum(50)
        self.height.setObjectName("height")
        self.width = QtWidgets.QSpinBox(Size_change_popup)
        self.width.setGeometry(QtCore.QRect(105, 65, 120, 30))
        self.width.setStyleSheet("background-color: rgb(223, 223, 223)")
        self.width.setKeyboardTracking(True)
        self.width.setMinimum(1)
        self.width.setMaximum(60)
        self.width.setObjectName("width")
        self.label_height = QtWidgets.QLabel(Size_change_popup)
        self.label_height.setGeometry(QtCore.QRect(20, 25, 80, 30))
        self.label_height.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.label_height.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_height.setObjectName("label_height")
        self.label_width = QtWidgets.QLabel(Size_change_popup)
        self.label_width.setGeometry(QtCore.QRect(20, 65, 80, 30))
        self.label_width.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.label_width.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_width.setObjectName("label_width")

        self.retranslateUi(Size_change_popup)
        self.buttonBox.accepted.connect(Size_change_popup.accept)
        self.buttonBox.rejected.connect(Size_change_popup.reject)
        QtCore.QMetaObject.connectSlotsByName(Size_change_popup)

    def retranslateUi(self, Size_change_popup):
        _translate = QtCore.QCoreApplication.translate
        Size_change_popup.setWindowTitle(_translate("Size_change_popup", "Zmiana wielkości"))
        self.label_height.setText(_translate("Size_change_popup", "Wysokość:"))
        self.label_width.setText(_translate("Size_change_popup", "Szerokość:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Size_change_popup = QtWidgets.QDialog()
    ui = Ui_Size_change_popup()
    ui.setupUi(Size_change_popup)
    Size_change_popup.show()
    sys.exit(app.exec())
